/**
 * Playwright Trace Parser
 *
 * Parses Playwright trace.zip files to extract execution context (page URL,
 * navigation history, frame hierarchy, console events, network, etc.).
 *
 * WHY THIS EXISTS
 * Playwright NATIVELY records rich execution metadata in the trace. By parsing
 * it in one place, we avoid duplicating trace-reading logic across:
 *   - Artifact collection (for healing URL resolution)
 *   - Replay / timeline features (navigation sequence, action log)
 *   - AI analysis (console/network errors, DOM snapshots)
 *
 * NO FIXTURE / CONFIG INJECTION NEEDED — the trace is auto-generated by the
 * `--trace=retain-on-failure` CLI flag (same category as `--reporter=json`).
 *
 * GRACEFUL: All methods return null/empty on error (missing trace, no unzip,
 * malformed file) so callers can fall back to their own defaults.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { execSync } from 'child_process';

/**
 * Execution context derived from a Playwright trace. Today: pageUrl. Tomorrow:
 * navigation sequence, frames, console, network, action timeline, DOM snapshots.
 */
export interface ExecutionContext {
  /** The rendered page URL at the time of the trace snapshot (most recent frame). */
  pageUrl: string | null;
  // Future extensions (all nullable):
  // navigationHistory?: string[];
  // frames?: FrameInfo[];
  // consoleEvents?: ConsoleEvent[];
  // networkRequests?: NetworkRequest[];
  // actionTimeline?: Action[];
  // domSnapshots?: DOMSnapshot[];
}

/**
 * Extract the REAL page URL from a Playwright trace.zip.
 *
 * HOW IT WORKS
 * Playwright records `frame-snapshot` events inside the trace containing the
 * rendered page's `frameUrl` (the document URL at each snapshot). We read the
 * LAST non-blank URL (the page at failure). Falls back to the navigation target
 * (`before` action with `params.url`) if no snapshot URL is present.
 *
 * WHY NOT A FIXTURE?
 * Empirical proof (see PR description): the JSON reporter and error-context.md
 * do NOT contain page.url(). The trace is Playwright's own execution-context
 * artifact — no fixture injection, no config rewrite, no test-code changes.
 *
 * Returns null on any error (missing trace, no unzip, malformed, no URL) so
 * callers can fall back to their own URL cascade (execution base URL / latest
 * active profile / etc.).
 */
export function extractPageUrl(traceZipPath: string): string | null {
  if (!traceZipPath || !fs.existsSync(traceZipPath)) return null;
  let tmpDir: string | null = null;
  try {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'levelup-trace-'));
    // `unzip` is present on the Playwright Docker image and standard Linux runners.
    execSync(`unzip -o "${traceZipPath}" -d "${tmpDir}"`, { stdio: 'ignore' });

    const traceFiles = fs.readdirSync(tmpDir).filter((f) => f.endsWith('.trace'));
    let lastPageUrl: string | null = null;
    let gotoUrl: string | null = null;

    for (const tf of traceFiles) {
      const lines = fs.readFileSync(path.join(tmpDir, tf), 'utf-8').split('\n');
      for (const line of lines) {
        const s = line.trim();
        if (!s) continue;
        let evt: any;
        try { evt = JSON.parse(s); } catch { continue; }
        // The rendered document URL at each snapshot — last non-blank wins (page at failure).
        if (evt.type === 'frame-snapshot') {
          const url = evt.snapshot?.frameUrl;
          if (url && url !== 'about:blank') lastPageUrl = url;
        }
        // Fallback: the navigation target if no snapshot URL is present.
        if (evt.type === 'before' && evt.params?.url) gotoUrl = evt.params.url;
      }
    }
    return lastPageUrl ?? gotoUrl;
  } catch (err) {
    return null;
  } finally {
    if (tmpDir) {
      try { fs.rmSync(tmpDir, { recursive: true, force: true }); } catch { /* noop */ }
    }
  }
}

/**
 * Parse a Playwright trace.zip into an ExecutionContext.
 *
 * Today: extracts pageUrl only. Future: extend to parse navigation, frames,
 * console, network, actions, DOM snapshots — all in one place, one trace unzip.
 *
 * Returns a context with nullable fields. Callers check `context.pageUrl` and
 * fall back to their own defaults if null.
 */
export function parse(traceZipPath: string): ExecutionContext {
  return {
    pageUrl: extractPageUrl(traceZipPath),
    // Future fields go here as they're implemented
  };
}
