/**
 * Selector Quality Engine
 * Ranks and generates the most reliable selectors for elements.
 * 
 * Priority hierarchy:
 * 1. data-testid (1.0) — Most stable, explicitly for testing
 * 2. role-based (0.9) — Semantic, accessibility-focused
 * 3. label-based (0.85) — User-visible, stable
 * 4. placeholder (0.7) — Fairly stable but can change
 * 5. stable CSS (0.6) — ID, name attribute
 * 6. text-based (0.5) — Visible text, can change with i18n
 * 7. CSS class (0.3) — Unstable, changes with styling
 * 8. XPath (0.1) — Fragile, avoid
 */

import type { PageElement } from './page-crawler';
import { logger } from '../utils/logger';

const MOD = 'selector-quality';

/* -------------------------------------------------------------------------- */
/*  Types                                                                     */
/* -------------------------------------------------------------------------- */

export interface ScoredSelector {
  selector: string;
  playwrightCode: string;     // e.g., page.getByRole('button', { name: 'Login' })
  score: number;              // 0.0 to 1.0
  strategy: SelectorStrategy;
  reason: string;
  isRecommended: boolean;
}

export type SelectorStrategy = 
  | 'data-testid' | 'role' | 'label' | 'placeholder' | 'name-attr'
  | 'id' | 'text' | 'css-class' | 'css-combined' | 'xpath' | 'nth-match';

export interface SelectorQualityReport {
  element: PageElement;
  selectors: ScoredSelector[];
  bestSelector: ScoredSelector;
  averageScore: number;
  hasStableSelector: boolean;  // score >= 0.7
}

/* -------------------------------------------------------------------------- */
/*  Engine                                                                    */
/* -------------------------------------------------------------------------- */

export class SelectorQualityEngine {
  /**
   * Generate and rank all possible selectors for an element.
   */
  rankSelectors(element: PageElement): SelectorQualityReport {
    const selectors: ScoredSelector[] = [];

    // 1. data-testid (best)
    if (element.dataTestId) {
      selectors.push({
        selector: `[data-testid="${element.dataTestId}"]`,
        playwrightCode: `page.getByTestId('${element.dataTestId}')`,
        score: 1.0,
        strategy: 'data-testid',
        reason: 'data-testid is the most stable selector strategy',
        isRecommended: true,
      });
    }

    // 2. Role-based
    const roleSelector = this.buildRoleSelector(element);
    if (roleSelector) {
      selectors.push(roleSelector);
    }

    // 3. Label-based
    if (element.nearbyLabel) {
      selectors.push({
        selector: `label:"${element.nearbyLabel}"`,
        playwrightCode: `page.getByLabel('${escapeQuotes(element.nearbyLabel)}')`,
        score: 0.85,
        strategy: 'label',
        reason: 'Label-based selectors are stable and semantic',
        isRecommended: true,
      });
    }

    // 4. Placeholder-based
    if (element.placeholder) {
      selectors.push({
        selector: `[placeholder="${element.placeholder}"]`,
        playwrightCode: `page.getByPlaceholder('${escapeQuotes(element.placeholder)}')`,
        score: 0.7,
        strategy: 'placeholder',
        reason: 'Placeholder text is fairly stable for form inputs',
        isRecommended: true,
      });
    }

    // 5. Name attribute
    if (element.name) {
      selectors.push({
        selector: `${element.tag}[name="${element.name}"]`,
        playwrightCode: `page.locator('${element.tag}[name="${element.name}"]')`,
        score: 0.65,
        strategy: 'name-attr',
        reason: 'Name attribute is stable for form elements',
        isRecommended: false,
      });
    }

    // 6. ID-based
    if (element.id && !isAutoGeneratedId(element.id)) {
      selectors.push({
        selector: `#${element.id}`,
        playwrightCode: `page.locator('#${element.id}')`,
        score: 0.6,
        strategy: 'id',
        reason: 'ID selector, stable if not auto-generated',
        isRecommended: false,
      });
    }

    // 7. Text-based (for buttons and links)
    if (element.textContent && ['button', 'a'].includes(element.tag)) {
      const text = element.textContent.trim().slice(0, 60);
      if (text.length >= 2) {
        selectors.push({
          selector: `text="${text}"`,
          playwrightCode: element.tag === 'a'
            ? `page.getByRole('link', { name: '${escapeQuotes(text)}' })`
            : `page.getByRole('button', { name: '${escapeQuotes(text)}' })`,
          score: 0.5,
          strategy: 'text',
          reason: 'Text-based selectors work but may break with i18n changes',
          isRecommended: false,
        });
      }
    }

    // 8. CSS class (least preferred)
    if (element.className && typeof element.className === 'string') {
      const stableClass = extractStableClass(element.className);
      if (stableClass) {
        selectors.push({
          selector: `${element.tag}.${stableClass}`,
          playwrightCode: `page.locator('${element.tag}.${stableClass}')`,
          score: 0.3,
          strategy: 'css-class',
          reason: 'CSS class selectors are fragile and change with styling updates',
          isRecommended: false,
        });
      }
    }

    // Sort by score descending
    selectors.sort((a, b) => b.score - a.score);

    // Mark top one as recommended if none are
    if (selectors.length > 0 && !selectors.some(s => s.isRecommended)) {
      selectors[0]!.isRecommended = true;
    }

    const bestSelector = selectors[0] || {
      selector: `${element.tag}`,
      playwrightCode: `page.locator('${element.tag}')`,
      score: 0.1,
      strategy: 'css-combined' as SelectorStrategy,
      reason: 'Fallback: no stable selector found',
      isRecommended: true,
    };

    const avgScore = selectors.length > 0
      ? selectors.reduce((sum, s) => sum + s.score, 0) / selectors.length
      : 0.1;

    return {
      element,
      selectors,
      bestSelector,
      averageScore: avgScore,
      hasStableSelector: selectors.some(s => s.score >= 0.7),
    };
  }

  /**
   * Get the best Playwright code for an element.
   */
  getBestPlaywrightSelector(element: PageElement): string {
    const report = this.rankSelectors(element);
    return report.bestSelector.playwrightCode;
  }

  /**
   * Score a collection of elements' selector quality.
   */
  scorePageSelectors(elements: PageElement[]): {
    averageScore: number;
    stablePercentage: number;
    weakSelectors: SelectorQualityReport[];
  } {
    const reports = elements.map(el => this.rankSelectors(el));
    const avgScore = reports.length > 0
      ? reports.reduce((sum, r) => sum + r.bestSelector.score, 0) / reports.length
      : 0;
    const stableCount = reports.filter(r => r.hasStableSelector).length;
    const stablePercentage = reports.length > 0 ? stableCount / reports.length : 0;
    const weakSelectors = reports.filter(r => r.bestSelector.score < 0.5);

    return { averageScore: avgScore, stablePercentage, weakSelectors };
  }

  private buildRoleSelector(el: PageElement): ScoredSelector | null {
    const role = el.role || el.ariaRole || inferRole(el);
    if (!role) return null;

    const name = el.ariaLabel || el.textContent?.trim().slice(0, 60) || el.nearbyLabel;
    const pwCode = name
      ? `page.getByRole('${role}', { name: '${escapeQuotes(name)}' })`
      : `page.getByRole('${role}')`;

    return {
      selector: name ? `role=${role}[name="${name}"]` : `role=${role}`,
      playwrightCode: pwCode,
      score: name ? 0.9 : 0.6,
      strategy: 'role',
      reason: name
        ? 'Role + name is a robust, accessible selector'
        : 'Role-only selector may match multiple elements',
      isRecommended: !!name,
    };
  }
}

/* -------------------------------------------------------------------------- */
/*  Helpers                                                                   */
/* -------------------------------------------------------------------------- */

function inferRole(el: PageElement): string | null {
  const tag = el.tag;
  const type = el.type;

  if (tag === 'button') return 'button';
  if (tag === 'a') return 'link';
  if (tag === 'input') {
    if (type === 'checkbox') return 'checkbox';
    if (type === 'radio') return 'radio';
    if (type === 'submit') return 'button';
    if (['text', 'email', 'password', 'search', 'tel', 'url', 'number'].includes(type || 'text')) {
      return 'textbox';
    }
  }
  if (tag === 'textarea') return 'textbox';
  if (tag === 'select') return 'combobox';
  if (tag === 'img') return 'img';
  if (tag === 'nav') return 'navigation';

  return null;
}

function isAutoGeneratedId(id: string): boolean {
  // IDs that look auto-generated: contain UUIDs, long hex, react-generated, etc.
  if (/^[a-f0-9]{8,}$/i.test(id)) return true;
  if (/^(react|\:r|\:R|\:)/.test(id)) return true;
  if (/^(ember|ng-|vue-)/.test(id)) return true;
  if (id.length > 30 && /[0-9]/.test(id)) return true;
  return false;
}

function extractStableClass(className: string): string | null {
  const classes = className.split(/\s+/);
  // Filter out utility classes, hashes, and auto-generated classes
  const stable = classes.filter(c => {
    if (c.length < 3) return false;
    if (/^[a-z]+-[a-f0-9]{4,}$/i.test(c)) return false;  // hash suffix
    if (/^(css-|sc-|emotion-|jss|makeStyles)/.test(c)) return false;  // CSS-in-JS
    if (/^(w-|h-|p-|m-|text-|bg-|flex|grid|border|rounded)/.test(c)) return false;  // Tailwind
    return true;
  });
  return stable[0] || null;
}

function escapeQuotes(s: string): string {
  return s.replace(/'/g, "\\'");
}
