/**
 * Regression test for Sprint 4 "Generation Quality" — COMMENT DISCIPLINE.
 *
 * The generated Playwright specs must be CODE, not prose. The framework already
 * owns Test Cases, RTM, App Knowledge and Coverage/RTM reports, so the spec
 * must NOT re-narrate any of that. The ONLY comments allowed in a generated spec
 * are:
 *   • `// @tc:TC<id>`         — the traceability marker (one per test)
 *   • `// TODO: …`            — an honest reviewer flag (low-confidence locator,
 *                               unmapped step, non-automatable caveat)
 *
 * Everything else — the `/** … *\/` doc/coverage header, per-step English
 * narration (`// Navigate to…`, `// Click the…`, `// Enter…`, `// Verify…`),
 * dataset/page-object narration — must be gone.
 *
 * Driven through the PUBLIC generate() entry point with cached crawl data so no
 * network/LLM is used.
 */
import { ScriptGenEngine } from '../../src/script-gen/script-gen-engine';

let passed = 0;
let failed = 0;
function ok(name: string, cond: boolean) {
  if (cond) { passed++; console.log(`  ✅ ${name}`); }
  else { failed++; console.log(`  ❌ ${name}`); }
}

const cachedCrawlData: any = {
  url: 'https://www.saucedemo.com', finalUrl: 'https://www.saucedemo.com',
  title: 'Swag Labs', pageType: 'login', pageTypeConfidence: 0.9,
  elements: [
    { tag: 'input', id: 'user-name', name: 'user-name', type: 'text', attributes: { 'data-test': 'username' } },
    { tag: 'input', id: 'password', name: 'password', type: 'password', attributes: { 'data-test': 'password' } },
    { tag: 'input', id: 'login-button', type: 'submit', attributes: { 'data-test': 'login-button' } },
  ],
  forms: [], navigationLinks: [], buttons: [], inputs: [], headings: [],
  htmlSnapshot: '', totalElements: 3, interactiveElements: 3,
};

// A positive case and two DISTINCT negative cases — exercises the single-case
// header path, the per-step narration paths, and the consolidated multi-case
// spec header path all at once.
const testCases: any[] = [
  { id: 1841, title: 'Valid credentials log in successfully', priority: 'P0',
    preconditions: 'On login page', test_data: '',
    expected_result: 'The user is redirected to the inventory page.',
    steps: ['Navigate to https://www.saucedemo.com', 'Enter a valid username', 'Enter a valid password', 'Click the login button'] },
  { id: 2001, title: 'Invalid password', priority: 'P1',
    preconditions: 'On login page', test_data: '',
    expected_result: 'An error message is displayed indicating credentials do not match.',
    steps: ['Navigate to https://www.saucedemo.com', 'Enter a valid username', 'Enter an invalid password', 'Click the login button'] },
  { id: 2002, title: 'Unknown user', priority: 'P1',
    preconditions: 'On login page', test_data: '',
    expected_result: 'An error message is displayed indicating credentials do not match.',
    steps: ['Navigate to https://www.saucedemo.com', 'Enter an unknown username', 'Enter a password', 'Click the login button'] },
];

async function main() {
  const engine = new ScriptGenEngine();
  const result = await engine.generate({ url: 'https://www.saucedemo.com', cachedCrawlData, testCases } as any);
  const specs = result.generatedFiles.filter(f => f.type === 'test');
  const all = specs.map(f => f.content).join('\n');

  console.log('=== Comment discipline (only @tc + TODO survive) ===');
  ok('at least one spec was generated', specs.length > 0);

  // No JSDoc-style doc/coverage header block anywhere.
  ok('no /** … */ doc block header', !/\/\*\*[\s\S]*?\*\//.test(all));
  ok('no "Test Case ID:" header line', !/Test Case ID:/.test(all));
  ok('no "Coverage:" header line', !/Coverage:/.test(all));
  ok('no "Repository Assets Reused:" header line', !/Repository Assets Reused:/.test(all));
  ok('no "Generated by" attribution', !/Generated by/i.test(all));
  ok('no "Consolidated spec" narration', !/Consolidated spec/.test(all));

  // No per-step English narration.
  ok('no "// Navigate" narration', !/\/\/\s*Navigate/i.test(all));
  ok('no "// Click" narration', !/\/\/\s*Click/i.test(all));
  ok('no "// Enter" narration', !/\/\/\s*Enter/i.test(all));
  ok('no "// Verify Expected Result" banner', !/\/\/\s*[─\-]*\s*Verify Expected Result/i.test(all));
  ok('no "// Test data bound" narration', !/\/\/\s*Test data bound/i.test(all));
  ok('no "// Reusing repo Page Object" narration', !/\/\/\s*Reusing repo/i.test(all));

  // The traceability marker IS present (one per test case).
  ok('emits // @tc:TC1841', /\/\/ @tc:TC1841/.test(all));
  ok('emits // @tc:TC2001', /\/\/ @tc:TC2001/.test(all));
  ok('emits // @tc:TC2002', /\/\/ @tc:TC2002/.test(all));

  // EVERY line-comment in the output is one of the two allowed forms.
  const commentLines = all.split('\n')
    .map(l => l.trim())
    .filter(l => l.startsWith('//'));
  const allowed = (l: string) => /^\/\/ @tc:TC\d+$/.test(l) || /^\/\/ TODO:/.test(l);
  const offenders = commentLines.filter(l => !allowed(l));
  if (offenders.length) console.log('    offending comments:', JSON.stringify(offenders.slice(0, 10)));
  ok('every line-comment is either // @tc: or // TODO:', offenders.length === 0);

  console.log(`\n──────── ${passed} passed, ${failed} failed ────────`);
  if (failed > 0) process.exit(1);
}
main().catch(e => { console.error(e); process.exit(1); });
