/**
 * Unit tests for GitHub Service & Routes
 */

import {
  GitHubService,
  type PRCreationRequest,
  type GitHubConnectionStatus,
  type GitHubRepo,
  type GitHubBranch,
  type PRCreationResult,
} from '../../src/integrations/github-service';

let passed = 0;
let failed = 0;

function assert(label: string, condition: boolean) {
  if (condition) {
    console.log(`  ✅ ${label}`);
    passed++;
  } else {
    console.log(`  ❌ ${label}`);
    failed++;
  }
}

console.log('\n==================================================');
console.log('GitHub Service Tests');
console.log('==================================================\n');

// ─── Type/Interface checks ───────────────────────────────────────

console.log('=== Type definitions ===');

const mockUser = {
  login: 'testuser',
  name: 'Test User',
  avatarUrl: 'https://avatars.githubusercontent.com/u/123',
  htmlUrl: 'https://github.com/testuser',
  scopes: ['repo', 'workflow'],
};
assert('GitHubUser has login field', typeof mockUser.login === 'string');
assert('GitHubUser has scopes array', Array.isArray(mockUser.scopes));

const mockRepo: GitHubRepo = {
  id: 1,
  name: 'test-repo',
  fullName: 'testuser/test-repo',
  private: false,
  defaultBranch: 'main',
  htmlUrl: 'https://github.com/testuser/test-repo',
  description: 'A test repo',
  language: 'TypeScript',
  updatedAt: '2026-01-01T00:00:00Z',
  owner: 'testuser',
};
assert('GitHubRepo has all required fields', !!mockRepo.fullName && !!mockRepo.defaultBranch);

const mockBranch: GitHubBranch = {
  name: 'main',
  sha: 'abc123',
  protected: true,
};
assert('GitHubBranch has name, sha, protected', !!mockBranch.name && !!mockBranch.sha);

const mockStatus: GitHubConnectionStatus = {
  connected: true,
  user: mockUser,
  rateLimit: { remaining: 4999, limit: 5000, resetsAt: '2026-01-01T01:00:00Z' },
};
assert('GitHubConnectionStatus connected with user', mockStatus.connected && !!mockStatus.user);

const disconnectedStatus: GitHubConnectionStatus = {
  connected: false,
  error: 'Token expired',
};
assert('GitHubConnectionStatus disconnected with error', !disconnectedStatus.connected && !!disconnectedStatus.error);

// ─── PR Creation Request validation ──────────────────────────────

console.log('\n=== PR Creation Request ===');

const validPR: PRCreationRequest = {
  repoOwner: 'testuser',
  repoName: 'test-repo',
  branchName: 'feature/test-scripts',
  title: 'Add generated test scripts',
  body: 'Generated by LevelUp AI',
  files: [
    { path: 'tests/login.spec.ts', content: 'test("login", () => {})' },
    { path: 'tests/dashboard.spec.ts', content: 'test("dashboard", () => {})' },
  ],
};
assert('Valid PR request has all required fields',
  !!validPR.repoOwner && !!validPR.repoName && !!validPR.branchName && validPR.files.length > 0);
assert('PR request files have path and content',
  validPR.files.every(f => !!f.path && !!f.content));

// ─── Branch name validation ──────────────────────────────────────

console.log('\n=== Branch name validation ===');

const validBranchNames = [
  'feature/test-scripts',
  'levelup/tests-login-42',
  'fix/bug-123',
  'main',
  'feat/auth-crawling_v2',
];
const invalidBranchNames = [
  'branch with spaces',
  'branch@special',
  'branch#hash',
];

const branchRegex = /^[\w\-./]+$/;
for (const name of validBranchNames) {
  assert(`Valid branch: "${name}"`, branchRegex.test(name));
}
for (const name of invalidBranchNames) {
  assert(`Invalid branch: "${name}"`, !branchRegex.test(name));
}

// ─── File path sanitization ──────────────────────────────────────

console.log('\n=== File path sanitization ===');

const safePaths = ['tests/login.spec.ts', 'e2e/dashboard.spec.ts', 'src/utils/helpers.ts'];
const dangerousPaths = ['../../../etc/passwd', '/root/.ssh/id_rsa', 'tests/../../secret'];

for (const p of safePaths) {
  assert(`Safe path: "${p}"`, !p.includes('..') && !p.startsWith('/'));
}
for (const p of dangerousPaths) {
  assert(`Blocked path: "${p}"`, p.includes('..') || p.startsWith('/'));
}

// ─── PR Result structure ─────────────────────────────────────────

console.log('\n=== PR Result structure ===');

const successResult: PRCreationResult = {
  success: true,
  prUrl: 'https://github.com/user/repo/pull/42',
  prNumber: 42,
  branchName: 'feature/tests',
  branchUrl: 'https://github.com/user/repo/tree/feature/tests',
  commitSha: 'abc123def456',
  filesCommitted: 3,
};
assert('Success result has prUrl and prNumber', !!successResult.prUrl && !!successResult.prNumber);
assert('Success result has commitSha', !!successResult.commitSha);

const failResult: PRCreationResult = {
  success: false,
  error: 'Repository not found',
};
assert('Failure result has error message', !failResult.success && !!failResult.error);

// ─── Service instantiation ───────────────────────────────────────

console.log('\n=== Service instantiation ===');

const service = new GitHubService();
assert('GitHubService can be instantiated', !!service);
assert('GitHubService has getConnectionStatus method', typeof service.getConnectionStatus === 'function');
assert('GitHubService has listRepos method', typeof service.listRepos === 'function');
assert('GitHubService has listBranches method', typeof service.listBranches === 'function');
assert('GitHubService has createPullRequest method', typeof service.createPullRequest === 'function');

// ─── Token security ─────────────────────────────────────────────

console.log('\n=== Security checks ===');

// Verify that the service module doesn't export raw token
const moduleExports = Object.keys(require('../../src/integrations/github-service'));
assert('Module does not export raw token getter', !moduleExports.includes('getToken'));
assert('Module exports GitHubService class', moduleExports.includes('GitHubService'));

// Verify PR result never includes token
const resultKeys = Object.keys(successResult);
assert('PR result does not contain token field', !resultKeys.includes('token'));
assert('PR result does not contain auth field', !resultKeys.includes('authorization'));

// ─── Summary ─────────────────────────────────────────────────────

console.log('\n==================================================');
console.log(`Results: ${passed} passed, ${failed} failed`);
if (failed === 0) console.log('All tests passed! ✅');
else {
  console.log('Some tests FAILED ❌');
  process.exit(1);
}
